import { incidentListSchema, type Incident } from "./schemas";

const now = Date.now();
const isoMinutesAgo = (minutes: number, secondsOffset = 0): string =>
  new Date(now - minutes * 60_000 + secondsOffset * 1_000).toISOString();

interface IncidentSeed {
  id: string;
  priority: Incident["priority"];
  category: Incident["category"];
  minutesAgo: number;
  address: string;
  district: string;
  coordinates: [number, number];
  summary: string;
  channel: Incident["channel"];
  callerConnection: Incident["callerConnection"];
  peopleCount?: number | null;
  injuries?: string;
  hazards?: string[];
  missingFields?: string[];
  status?: Incident["status"];
  claimedBy?: string | null;
  destinationAgency?: string;
  requestedResponse?: string;
  failureReason?: string;
}

const makeIncident = (seed: IncidentSeed): Incident => {
  const receivedAt = isoMinutesAgo(seed.minutesAgo);
  const transcript = [
    {
      id: `${seed.id}-t1`,
      speaker: "CALLER" as const,
      original: seed.summary,
      timestamp: isoMinutesAgo(seed.minutesAgo, 4),
      factIds: ["summary"],
    },
    {
      id: `${seed.id}-t2`,
      speaker: "AI" as const,
      original: `I have your location as ${seed.address}. Is that correct?`,
      timestamp: isoMinutesAgo(seed.minutesAgo, 10),
      factIds: ["address"],
    },
  ];

  return {
    id: seed.id,
    version: 1,
    category: seed.category,
    priority: seed.priority,
    status: seed.status ?? "NEEDS_REVIEW",
    summary: seed.summary,
    location: {
      address: seed.address,
      district: seed.district,
      coordinates: seed.coordinates,
    },
    channel: seed.channel,
    callerConnection: seed.callerConnection,
    peopleCount: seed.peopleCount ?? null,
    injuries: seed.injuries ?? "Not reported",
    hazards: seed.hazards ?? [],
    accessibilityNeeds: [],
    destinationAgency: seed.destinationAgency ?? "Metro Emergency Communications",
    requestedResponse: seed.requestedResponse ?? "Assess and dispatch appropriate unit",
    missingFields: seed.missingFields ?? [],
    claimedBy: seed.claimedBy ?? null,
    viewers: seed.claimedBy ? [seed.claimedBy] : [],
    receivedAt,
    updatedAt: isoMinutesAgo(Math.max(seed.minutesAgo - 1, 0)),
    transcript,
    evidence: [],
    activity: [
      {
        id: `${seed.id}-a1`,
        timestamp: receivedAt,
        actor: "Crisis Mesh",
        action: "Incident created",
        detail: `${seed.channel.toLowerCase()} intake opened`,
      },
      {
        id: `${seed.id}-a2`,
        timestamp: isoMinutesAgo(seed.minutesAgo, 12),
        actor: "Triage AI",
        action: "Initial extraction complete",
      },
    ],
    recommendation: {
      agency: seed.destinationAgency ?? "Metro Emergency Communications",
      units: seed.category === "MEDICAL" ? ["ALS Ambulance", "Engine"] : ["Nearest response unit"],
      etaMinutes: seed.priority === "CRITICAL" ? 4 : seed.priority === "URGENT" ? 7 : 12,
      rationale: "Closest available resources matched to reported incident type and hazards.",
    },
    failureReason: seed.failureReason,
  };
};

const primary = makeIncident({
  id: "CM-0722-0017",
  priority: "CRITICAL",
  category: "FIRE",
  minutesAgo: 18,
  address: "1428 W 21st St, Building C, Apt 4B",
  district: "Central / Sector 12",
  coordinates: [-87.6638, 41.8547],
  summary:
    "Smoke is filling a fourth-floor apartment after an electrical panel sparked. Three people are inside; one uses a wheelchair and one has smoke inhalation symptoms.",
  channel: "PHONE",
  callerConnection: "CONNECTED",
  peopleCount: 3,
  injuries: "1 adult coughing and dizzy from smoke exposure",
  hazards: ["Active electrical fire", "Heavy smoke", "Fourth-floor access"],
  missingFields: ["Sprinkler activation unknown"],
  status: "NEEDS_REVIEW",
  destinationAgency: "Chicago Fire Department",
  requestedResponse: "Structure fire response with EMS and accessible evacuation support",
});

primary.version = 7;
primary.accessibilityNeeds = ["Wheelchair evacuation assistance"];
primary.viewers = ["M. Chen", "R. Singh"];
primary.transcript = [
  {
    id: "CM-0722-0017-t1",
    speaker: "AI",
    original: "911 emergency. Tell me what is happening.",
    timestamp: isoMinutesAgo(18, 2),
    factIds: [],
  },
  {
    id: "CM-0722-0017-t2",
    speaker: "CALLER",
    original: "Hay humo por todas partes. El panel eléctrico explotó en la pared.",
    translated: "There is smoke everywhere. The electrical panel exploded in the wall.",
    language: "Spanish",
    timestamp: isoMinutesAgo(18, 7),
    factIds: ["summary", "hazards", "category"],
  },
  {
    id: "CM-0722-0017-t3",
    speaker: "AI",
    original: "How many people are inside, and is anyone hurt?",
    timestamp: isoMinutesAgo(18, 14),
    factIds: [],
  },
  {
    id: "CM-0722-0017-t4",
    speaker: "CALLER",
    original: "Somos tres. Mi padre está tosiendo y mareado. Mi hermana usa silla de ruedas.",
    translated: "There are three of us. My father is coughing and dizzy. My sister uses a wheelchair.",
    language: "Spanish",
    timestamp: isoMinutesAgo(18, 21),
    factIds: ["peopleCount", "injuries", "accessibilityNeeds"],
  },
  {
    id: "CM-0722-0017-t5",
    speaker: "AI",
    original: "Confirm your address and apartment number.",
    timestamp: isoMinutesAgo(18, 29),
    factIds: [],
  },
  {
    id: "CM-0722-0017-t6",
    speaker: "CALLER",
    original: "1428 West 21st, edificio C, apartamento 4B. Estamos en el cuarto piso.",
    translated: "1428 West 21st, Building C, apartment 4B. We are on the fourth floor.",
    language: "Spanish",
    timestamp: isoMinutesAgo(18, 34),
    factIds: ["address", "hazards"],
  },
  {
    id: "CM-0722-0017-t7",
    speaker: "AI",
    original: "Move away from the panel, stay low, and go to the balcony if the hallway is blocked. Help is being prepared.",
    timestamp: isoMinutesAgo(17, 45),
    factIds: [],
  },
];
primary.evidence = [
  {
    id: "CM-0722-0017-e1",
    type: "PHOTO",
    label: "Electrical panel and smoke",
    timestamp: isoMinutesAgo(15),
  },
  {
    id: "CM-0722-0017-e2",
    type: "AUDIO",
    label: "Caller recording",
    timestamp: isoMinutesAgo(18),
    durationSeconds: 126,
  },
  {
    id: "CM-0722-0017-e3",
    type: "PHOTO",
    label: "Hallway visibility",
    timestamp: isoMinutesAgo(14),
  },
];
primary.activity = [
  {
    id: "CM-0722-0017-a1",
    timestamp: isoMinutesAgo(18),
    actor: "Crisis Mesh",
    action: "Voice call connected",
    detail: "Automatic language detection: Spanish (98%)",
  },
  {
    id: "CM-0722-0017-a2",
    timestamp: isoMinutesAgo(17, 30),
    actor: "Triage AI",
    action: "Priority raised to critical",
    detail: "Fire, smoke exposure, and mobility constraint detected",
  },
  {
    id: "CM-0722-0017-a3",
    timestamp: isoMinutesAgo(15),
    actor: "Caller",
    action: "Evidence uploaded",
    detail: "3 items received",
  },
  {
    id: "CM-0722-0017-a4",
    timestamp: isoMinutesAgo(3),
    actor: "M. Chen",
    action: "Opened incident",
  },
];
primary.recommendation = {
  agency: "Chicago Fire Department",
  units: ["2 Engines", "1 Truck", "ALS Ambulance", "Accessible transport"],
  etaMinutes: 4,
  rationale: "Reported structure fire with smoke injury and a mobility-assisted evacuation on floor four.",
};

export const demoIncidents = incidentListSchema.parse([
  primary,
  makeIncident({
    id: "CM-0722-0024",
    priority: "CRITICAL",
    category: "MEDICAL",
    minutesAgo: 11,
    address: "55 E Monroe St, Lobby",
    district: "Central / Sector 03",
    coordinates: [-87.6253, 41.8807],
    summary: "Adult collapsed in an office lobby, not responding normally; bystander has started CPR.",
    channel: "PHONE",
    callerConnection: "CONNECTED",
    peopleCount: 1,
    injuries: "Unresponsive; abnormal breathing",
    hazards: [],
    missingFields: ["AED status"],
    status: "CLAIMED",
    claimedBy: "D. Alvarez",
    destinationAgency: "Chicago Fire Department EMS",
    requestedResponse: "Cardiac arrest response",
  }),
  makeIncident({
    id: "CM-0722-0031",
    priority: "CRITICAL",
    category: "RESCUE",
    minutesAgo: 6,
    address: "I-90 EB at Exit 51H",
    district: "Highway / Sector 07",
    coordinates: [-87.6544, 41.8886],
    summary: "Multi-vehicle crash with one person trapped and fuel leaking from a pickup truck.",
    channel: "WEB",
    callerConnection: "CONNECTED",
    peopleCount: 4,
    injuries: "At least 2 injured; severity unclear",
    hazards: ["Fuel leak", "Live traffic"],
    missingFields: ["Exact vehicle count"],
    status: "INTAKE",
    destinationAgency: "Chicago Fire Department",
    requestedResponse: "Extrication, EMS, and traffic control",
  }),
  makeIncident({
    id: "CM-0722-0044",
    priority: "URGENT",
    category: "HAZMAT",
    minutesAgo: 23,
    address: "810 N Ashland Ave",
    district: "West / Sector 09",
    coordinates: [-87.6678, 41.8967],
    summary: "Strong natural gas odor reported in a six-unit residential building basement.",
    channel: "PHONE",
    callerConnection: "UNSTABLE",
    peopleCount: null,
    hazards: ["Possible gas leak"],
    missingFields: ["Occupant count", "Evacuation status"],
    destinationAgency: "Chicago Fire Department",
  }),
  makeIncident({
    id: "CM-0722-0052",
    priority: "URGENT",
    category: "POLICE",
    minutesAgo: 19,
    address: "Humboldt Park, Boat House",
    district: "West / Sector 14",
    coordinates: [-87.7012, 41.9058],
    summary: "Parent cannot locate a seven-year-old last seen near the boat house ten minutes ago.",
    channel: "SMS",
    callerConnection: "CONNECTED",
    peopleCount: 1,
    missingFields: ["Child clothing description"],
    claimedBy: "S. Brooks",
    status: "CLAIMED",
    destinationAgency: "Chicago Police Department",
    requestedResponse: "Missing child search",
  }),
  makeIncident({
    id: "CM-0722-0061",
    priority: "URGENT",
    category: "MEDICAL",
    minutesAgo: 14,
    address: "233 S Wacker Dr, Floor 18",
    district: "Central / Sector 01",
    coordinates: [-87.6359, 41.8789],
    summary: "Older adult fell down four stairs and reports severe hip pain; conscious and alert.",
    channel: "WEB",
    callerConnection: "ENDED",
    peopleCount: 1,
    injuries: "Possible hip fracture",
    missingFields: ["Blood thinner use"],
    destinationAgency: "Chicago Fire Department EMS",
  }),
  makeIncident({
    id: "CM-0722-0068",
    priority: "URGENT",
    category: "RESCUE",
    minutesAgo: 12,
    address: "Lower Wacker Dr at Columbus",
    district: "Central / Sector 04",
    coordinates: [-87.6204, 41.8871],
    summary: "Sedan stalled in rising water; two occupants remain inside and water is above the tires.",
    channel: "PHONE",
    callerConnection: "DISCONNECTED",
    peopleCount: 2,
    hazards: ["Rising water", "Limited access"],
    missingFields: ["Water current"],
    destinationAgency: "Chicago Fire Department",
    requestedResponse: "Water rescue response",
  }),
  makeIncident({
    id: "CM-0722-0074",
    priority: "URGENT",
    category: "POLICE",
    minutesAgo: 9,
    address: "3900 S Michigan Ave, Unit 2",
    district: "South / Sector 22",
    coordinates: [-87.6231, 41.8232],
    summary: "Neighbor reports shouting and breaking glass next door; possible domestic disturbance.",
    channel: "SMS",
    callerConnection: "CONNECTED",
    hazards: ["Unknown weapons"],
    missingFields: ["People involved", "Weapon confirmation"],
    destinationAgency: "Chicago Police Department",
    requestedResponse: "Priority welfare and safety check",
  }),
  makeIncident({
    id: "CM-0722-0080",
    priority: "URGENT",
    category: "MEDICAL",
    minutesAgo: 8,
    address: "1060 W Addison St, Gate 3",
    district: "North / Sector 05",
    coordinates: [-87.6555, 41.9474],
    summary: "Teen with known peanut allergy has facial swelling after eating; epinephrine given once.",
    channel: "PHONE",
    callerConnection: "CONNECTED",
    peopleCount: 1,
    injuries: "Facial swelling and difficulty swallowing",
    missingFields: ["Second epinephrine dose available"],
    destinationAgency: "Chicago Fire Department EMS",
    requestedResponse: "Advanced life support ambulance",
  }),
  makeIncident({
    id: "CM-0722-0091",
    priority: "URGENT",
    category: "RESCUE",
    minutesAgo: 4,
    address: "401 N State St, Elevator 4",
    district: "Central / Sector 02",
    coordinates: [-87.6277, 41.8892],
    summary: "Five people trapped in a stalled elevator; one reports chest tightness and panic symptoms.",
    channel: "WEB",
    callerConnection: "CONNECTED",
    peopleCount: 5,
    injuries: "One person with chest tightness",
    missingFields: ["Elevator floor position"],
    status: "FAILED",
    destinationAgency: "Chicago Fire Department",
    requestedResponse: "Elevator rescue and EMS assessment",
    failureReason: "CAD gateway rejected unit code R-ELV-02.",
  }),
  makeIncident({
    id: "CM-0722-0102",
    priority: "ROUTINE",
    category: "WELFARE",
    minutesAgo: 31,
    address: "1840 N Milwaukee Ave, Apt 3A",
    district: "Northwest / Sector 11",
    coordinates: [-87.6851, 41.9149],
    summary: "Building manager requests a welfare check after newspapers accumulated for four days.",
    channel: "WEB",
    callerConnection: "ENDED",
    missingFields: ["Resident emergency contact"],
    destinationAgency: "Chicago Police Department",
    requestedResponse: "Welfare check",
  }),
  makeIncident({
    id: "CM-0722-0110",
    priority: "ROUTINE",
    category: "OTHER",
    minutesAgo: 17,
    address: "N Damen Ave at W Leland Ave",
    district: "North / Sector 08",
    coordinates: [-87.6791, 41.9668],
    summary: "Large tree limb is blocking one traffic lane; no vehicles or power lines are involved.",
    channel: "WEB",
    callerConnection: "ENDED",
    peopleCount: 0,
    missingFields: [],
    destinationAgency: "Chicago Department of Streets and Sanitation",
    requestedResponse: "Remove roadway obstruction",
  }),
  makeIncident({
    id: "CM-0722-0119",
    priority: "ROUTINE",
    category: "FIRE",
    minutesAgo: 10,
    address: "2700 W North Ave, Rear Alley",
    district: "West / Sector 10",
    coordinates: [-87.6949, 41.9102],
    summary: "Intermittent sparks heard from a utility transformer; no smoke or outage reported.",
    channel: "PHONE",
    callerConnection: "CONNECTED",
    hazards: ["Electrical equipment"],
    missingFields: ["Utility pole number"],
    destinationAgency: "ComEd Emergency Services",
    requestedResponse: "Electrical equipment inspection",
  }),
  makeIncident({
    id: "CM-0722-0126",
    priority: "ROUTINE",
    category: "MEDICAL",
    minutesAgo: 3,
    address: "500 W Madison St, Concourse",
    district: "Central / Sector 01",
    coordinates: [-87.6406, 41.8816],
    summary: "Traveler left temperature-controlled medication on a commuter train and needs assistance.",
    channel: "SMS",
    callerConnection: "CONNECTED",
    peopleCount: 1,
    missingFields: ["Medication name", "Time sensitivity"],
    destinationAgency: "Metra Police",
    requestedResponse: "Locate medication and advise caller",
  }),
]);
